--- #YAML:1.0
name:                Lab-VISA
version:             1.12
abstract:            Perl interface to National Instrument's VISA library
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Daniel Schroeer <schroeer@cpan.org>
