---
abstract: 'Perl interface to National Instruments VISA library'
author:
  - 'Daniel Schröer <schroeer@cpan.org>'
  - 'Andreas K. Hüttel <mail@akhuettel.de>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lab-VISA
no_index:
  directory:
    - t
    - inc
requires: {}
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Lab-VISA
  homepage: http://www.labmeasurement.de/
  x_MailingList: lab-visa-users@mailman.uni-regensburg.de
version: 2.95
